# Generated by Django 5.2.4 on 2025-07-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_options_alter_userprofile_options_and_more'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-referred_at'], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['code'], name='management__code_595921_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referee'], name='management__referee_39988c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer'], name='management__referre_b4be09_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('referee',), name='unique_referral_per_user'),
        ),
    ]
