# Generated by Django 3.2 on 2025-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20250222_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
