# Generated by Django 3.2 on 2025-02-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20250222_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='wallet_address',
        ),
    ]
