# Generated by Django 3.2 on 2025-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('advanced', 'Advanced')], max_length=50),
        ),
    ]
