# Generated by Django 3.2 on 2025-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('XRP', 'XRP'), ('USDT', 'USDT'), ('USD', 'USD')], default='BTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='crypto_currency',
            field=models.CharField(blank=True, choices=[('BTC', 'BTC'), ('XRP', 'XRP'), ('USDT', 'USDT'), ('USD', 'USD')], max_length=50, null=True),
        ),
    ]
